// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6fBYm4vRBxS3dLZKEeqv43DQ5lLo80Ic',
    appId: '1:143170925858:web:4537dd27a2e9ee6fe0617b',
    messagingSenderId: '143170925858',
    projectId: 'patricksnack-e3038',
    authDomain: 'patricksnack-e3038.firebaseapp.com',
    storageBucket: 'patricksnack-e3038.firebasestorage.app',
    measurementId: 'G-7W92TJHPGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClBgd-ioXCNZxdhYYCYPY8Z45iEByx3Gg',
    appId: '1:143170925858:android:886231ec378f2113e0617b',
    messagingSenderId: '143170925858',
    projectId: 'patricksnack-e3038',
    storageBucket: 'patricksnack-e3038.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0gpWDIsal5cSja4hdjzuEruWQsTwTRUI',
    appId: '1:143170925858:ios:83cfdc47538f6f3fe0617b',
    messagingSenderId: '143170925858',
    projectId: 'patricksnack-e3038',
    storageBucket: 'patricksnack-e3038.firebasestorage.app',
    iosBundleId: 'com.example.patrickSnackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6fBYm4vRBxS3dLZKEeqv43DQ5lLo80Ic',
    appId: '1:143170925858:web:9d66983ff8803818e0617b',
    messagingSenderId: '143170925858',
    projectId: 'patricksnack-e3038',
    authDomain: 'patricksnack-e3038.firebaseapp.com',
    storageBucket: 'patricksnack-e3038.firebasestorage.app',
    measurementId: 'G-YWBY9VZKQ7',
  );
}
